// ============================================================
// Contenu pédagogique — source unique de vérité.
// Transformé en JSON (src/data/) par validate-data.mjs après
// vérification : légalité (chess.js) + qualité (Stockfish).
// ============================================================

// solution : ligne complète en SAN. Coups d'indice pair = joués par
// l'utilisateur (camp au trait dans le FEN), impairs = réponses auto.

export const EXERCISES = [
  // ===== TACTIQUE — fourchette =====
  {
    id: 'tac-fourchette-0001', theme: 'tactique', subtheme: 'fourchette', difficulty: 800,
    fen: 'r3k3/8/8/1N6/8/8/6P1/4K3 w - - 0 1',
    solution: ['Nc7+', 'Kd7', 'Nxa8'],
    explanation: "La fourchette royale : le cavalier saute en c7 en faisant échec au roi et en attaquant la tour a8. Après le déplacement du roi, le cavalier capture la tour.",
    hint: "Un cavalier peut attaquer deux pièces à la fois. Visez la case c7.",
  },
  {
    id: 'tac-fourchette-0002', theme: 'tactique', subtheme: 'fourchette', difficulty: 1000,
    fen: '6k1/3q1pp1/8/8/4N3/8/6PP/4K3 w - - 0 1',
    solution: ['Nf6+', 'Kh8', 'Nxd7'],
    explanation: "Cf6+ est une fourchette entre le roi g8 et la dame d7. Le roi doit bouger, et le cavalier récolte la dame au coup suivant.",
    hint: "Le cavalier blanc peut donner échec tout en visant la dame noire.",
  },
  {
    id: 'tac-fourchette-0003', theme: 'tactique', subtheme: 'fourchette', difficulty: 950,
    fen: '7k/8/2n1b3/8/3P4/8/8/4K3 w - - 0 1',
    solution: ['d5'],
    explanation: "Les pions aussi font des fourchettes ! d5 attaque simultanément le cavalier c6 et le fou e6 : l'un des deux est perdu.",
    hint: "Avancez le pion qui touche deux pièces ennemies.",
  },
  {
    id: 'tac-fourchette-0004', theme: 'tactique', subtheme: 'fourchette', difficulty: 1050,
    fen: '7k/8/8/3r1n2/8/8/4P3/4K3 w - - 0 1',
    solution: ['e4'],
    explanation: "e4 ! attaque la tour d5 et le cavalier f5 en même temps — et aucun des deux ne peut capturer le pion. La fourchette de pion : économique et mortelle.",
    hint: "Le pion e2 peut frapper deux pièces à la fois en avançant de deux cases.",
  },
  {
    id: 'tac-fourchette-0005', theme: 'tactique', subtheme: 'fourchette', difficulty: 1450,
    fen: '2q3k1/8/8/5N2/8/8/8/6K1 w - - 0 1',
    solution: ['Ne7+', 'Kh8', 'Nxc8'],
    explanation: "Ce7+ fourche le roi g8 et la dame c8. Un motif classique : la dame noire n'a pas le temps de se sauver car son roi est en échec.",
    hint: "Le cavalier blanc peut donner échec en attaquant la dame.",
  },

  // ===== TACTIQUE — clouage =====
  {
    id: 'tac-clouage-0001', theme: 'tactique', subtheme: 'clouage', difficulty: 900,
    fen: 'r1bqk2r/pppp1ppp/5n2/4p1B1/8/5N2/PPPP1PPP/RN1QK2R w KQkq - 0 1',
    solution: ['Nxe5'],
    explanation: "Le cavalier f6 est cloué par le fou g5 sur la dame d8 : il ne peut pas bouger. Le pion e5 n'est donc pas réellement défendu — Cxe5 gagne un pion en toute sécurité.",
    hint: "Un défenseur cloué ne défend plus rien.",
  },
  {
    id: 'tac-clouage-0002', theme: 'tactique', subtheme: 'clouage', difficulty: 950,
    fen: 'r1bqk2r/pppp1ppp/5n2/6B1/4P3/8/PPPP1PPP/RN1QK2R w KQkq - 0 1',
    solution: ['e5'],
    explanation: "e5 attaque le cavalier f6, qui est cloué sur la dame d8 par le fou g5 et ne peut absolument pas bouger. Le cavalier est perdu.",
    hint: "Attaquez la pièce clouée avec un pion.",
  },
  {
    id: 'tac-clouage-0003', theme: 'tactique', subtheme: 'clouage', difficulty: 1100,
    fen: '4k3/1p6/2n5/8/BP6/8/8/4K3 w - - 0 1',
    solution: ['b5'],
    explanation: "Le cavalier c6 est cloué par le fou a4 sur le roi e8 : même défendu par le pion b7, il ne peut pas bouger. b5 ! le gagne — une pièce clouée est une pièce perdue si on l'attaque assez.",
    hint: "Attaquez le cavalier cloué avec le pion b.",
  },
  {
    id: 'tac-clouage-0004', theme: 'tactique', subtheme: 'clouage', difficulty: 1200,
    fen: 'r1bqk2r/pp1p1ppp/5n2/6B1/4P3/8/PPPP1PPP/RN1QK2R w KQkq - 0 1',
    solution: ['e5'],
    explanation: "Le cavalier f6 est cloué sur la dame d8 par le fou g5 : bouger le cavalier livrerait la dame (Fxd8). e5 ! gagne donc le cavalier pour un simple pion.",
    hint: "Un défenseur cloué ne défend plus : attaquez le cavalier avec le pion e.",
  },
  {
    id: 'tac-clouage-0005', theme: 'tactique', subtheme: 'clouage', difficulty: 1300,
    fen: 'r1bqkb1r/pppp1ppp/2n5/8/2B1n3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: ['Qe2', 'd5', 'd3'],
    explanation: "Le cavalier e4 est cloué sur la colonne e contre son propre roi : il ne peut pas bouger ! De2 le fixe, les Noirs le défendent par d5, mais d3 l'attaque au pion — il est perdu.",
    hint: "La dame peut clouer le cavalier e4 sur son roi via la colonne e.",
  },

  // ===== TACTIQUE — enfilade =====
  {
    id: 'tac-enfilade-0001', theme: 'tactique', subtheme: 'enfilade', difficulty: 900,
    fen: '7r/6k1/8/8/8/8/5B2/6K1 w - - 0 1',
    solution: ['Bd4+', 'Kg8', 'Bxh8'],
    explanation: "Fd4+ place le roi g7 en enfilade avec la tour h8 sur la grande diagonale. Le roi doit bouger, et le fou capture la tour derrière.",
    hint: "Alignez le fou avec le roi… et regardez ce qu'il y a derrière.",
  },
  {
    id: 'tac-enfilade-0002', theme: 'tactique', subtheme: 'enfilade', difficulty: 950,
    fen: '4r3/8/4k3/8/8/8/8/R5K1 w - - 0 1',
    solution: ['Re1+', 'Kd6', 'Rxe8'],
    explanation: "Te1+ met le roi e6 en échec. Derrière lui, sur la même colonne, se trouve la tour e8 : quand le roi s'écarte, la tour est prise.",
    hint: "Échec à la tour… puis capture derrière le roi.",
  },
  {
    id: 'tac-enfilade-0003', theme: 'tactique', subtheme: 'enfilade', difficulty: 1050,
    fen: '8/8/4k3/8/8/8/q7/2R2BK1 w - - 0 1',
    solution: ['Bc4+', 'Kd6', 'Bxa2'],
    explanation: "Fc4+ enfile le roi e6 et la dame a2. Si la dame capture le fou (Dxc4 ??), Txc4 la reprend : les blancs gagnent la dame dans tous les cas.",
    hint: "La tour c1 protège la case c4.",
  },
  {
    id: 'tac-enfilade-0004', theme: 'tactique', subtheme: 'enfilade', difficulty: 1150,
    fen: '6r1/5k2/8/8/8/8/8/5B1K w - - 0 1',
    solution: ['Bc4+', 'Kg7', 'Bxg8'],
    explanation: "Fc4+ enfile le roi f7 et la tour g8 sur la diagonale a2-g8. Le roi s'écarte et la tour tombe.",
    hint: "La diagonale c4-g8 passe par le roi… et finit sur la tour.",
  },

  // ===== TACTIQUE — attaque découverte =====
  {
    id: 'tac-decouverte-0001', theme: 'tactique', subtheme: 'decouverte', difficulty: 1000,
    fen: '3q2k1/4p1pp/8/3N4/8/8/8/3R2K1 w - - 0 1',
    solution: ['Nf6+', 'gxf6', 'Rxd8'],
    explanation: "Cf6+ ! : le cavalier donne échec et découvre l'attaque de la tour d1 sur la dame d8. La dame ne peut pas prendre le cavalier (le pion e7 bloque sa diagonale) : après gxf6, Txd8.",
    hint: "Bougez le cavalier en donnant échec pour libérer la colonne d.",
  },
  {
    id: 'tac-decouverte-0002', theme: 'tactique', subtheme: 'decouverte', difficulty: 1100,
    fen: '6k1/4q3/8/8/4B3/8/8/4R1K1 w - - 0 1',
    solution: ['Bd5+', 'Kh8', 'Rxe7'],
    explanation: "Fd5+ : le fou donne échec et découvre en même temps l'attaque de la tour e1 sur la dame e7. Après le déplacement du roi, Txe7 gagne la dame.",
    hint: "Le fou peut donner échec en découvrant la colonne e.",
  },
  {
    id: 'tac-decouverte-0003', theme: 'tactique', subtheme: 'decouverte', difficulty: 1300,
    fen: '4q1k1/6pp/8/8/4N3/8/8/4R1K1 w - - 0 1',
    solution: ['Nf6+', 'gxf6', 'Rxe8'],
    explanation: "Cf6+ ! : échec au roi plus découverte de la tour e1 sur la dame e8. La dame ne peut ni prendre le cavalier (hors de portée) ni rester en place : après gxf6, Txe8.",
    hint: "Bougez le cavalier avec échec pour ouvrir la colonne e.",
  },

  // ===== TACTIQUE — zwischenzug =====
  {
    id: 'tac-zwischenzug-0001', theme: 'tactique', subtheme: 'zwischenzug', difficulty: 1350,
    fen: 'r1bqk2r/pppp1ppp/2n2n2/8/2BPn3/2b5/PP3PPP/R1BQ1RK1 w kq - 0 1',
    solution: ['d5'],
    explanation: "Au lieu de reprendre bêtement le fou c3 (bxc3), les blancs insèrent l'entre-coup d5 !! qui attaque le cavalier c6 en gagnant un temps : le fou c3 restera pendu. Ce zwischenzug renverse l'ordre « attendu » des coups.",
    hint: "Le cavalier c6 est attaquable en plein centre — avant de reprendre en c3.",
  },

  // ===== TACTIQUE — sacrifices et mats =====
  {
    id: 'tac-sacrifice-0001', theme: 'tactique', subtheme: 'sacrifice', difficulty: 750,
    fen: '6k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: ['Rd8#'],
    explanation: "Mat du couloir : le roi noir est emmuré derrière ses trois pions. Td8 est mat immédiat — aucune case de fuite, aucune parade.",
    hint: "Le roi noir n'a aucune case de fuite sur la 8e rangée.",
  },
  {
    id: 'tac-sacrifice-0002', theme: 'tactique', subtheme: 'sacrifice', difficulty: 800,
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p2Q/2B5/8/PPPP1PPP/RNB1K1NR w KQkq - 0 1',
    solution: ['Qxf7#'],
    explanation: "Le mat du berger : Dxf7 est protégée par le fou c4, et le roi n'a aucune fuite. Leçon : f7 n'est défendu que par le roi en début de partie — c'est le point faible.",
    hint: "La dame et le fou c4 visent le même pion.",
  },
  {
    id: 'tac-sacrifice-0003', theme: 'tactique', subtheme: 'sacrifice', difficulty: 1100,
    fen: 'r5k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ['Qe8+', 'Rxe8', 'Rxe8#'],
    explanation: "Déviation sacrificielle : De8+ ! force Txe8, puis Txe8 est mat — la tour noire a été détournée de la défense de la case e8 par… elle-même.",
    hint: "Sacrifiez la dame pour attirer la tour sur une case fatale.",
  },
  {
    id: 'tac-sacrifice-0004', theme: 'tactique', subtheme: 'sacrifice', difficulty: 1250,
    fen: '5rk1/6pp/8/8/8/4R3/8/4R2K w - - 0 1',
    solution: ['Re8+', 'Rxe8', 'Rxe8#'],
    explanation: "Les tours doublées percent la 8e rangée : Te8+ force Txe8, puis la seconde tour reprend et mate — le roi g8 est bloqué par ses propres pions.",
    hint: "Sacrifiez la première tour pour ouvrir la dernière rangée.",
  },
  {
    id: 'tac-sacrifice-0005', theme: 'tactique', subtheme: 'sacrifice', difficulty: 1500,
    fen: 'r2qkbnr/ppp2ppp/2np4/4p2b/2B1P3/2N2N1P/PPPP1PP1/R1BQK2R w KQkq - 0 1',
    solution: ['Nxe5', 'Bxd1', 'Bxf7+', 'Ke7', 'Nd5#'],
    explanation: "Le mat de Légal : Cxe5 !! abandonne la dame. Si Fxd1 ??, Fxf7+ Re7, Cd5 est mat ! Le cavalier e5, le fou c4 et le cavalier c3 étouffent le roi au centre. Une leçon éternelle sur les dangers de la capture gourmande.",
    hint: "Le cavalier f6 est cloué… mais est-ce vraiment un problème ?",
  },
  {
    id: 'tac-sacrifice-0006', theme: 'tactique', subtheme: 'sacrifice', difficulty: 900,
    fen: '7k/6pp/5N2/8/8/8/8/K6R w - - 0 1',
    solution: ['Rxh7#'],
    explanation: "Le mat arabe : Txh7 ! est mat — la tour est protégée par le cavalier f6, qui couvre aussi la case de fuite g8. Le duo tour + cavalier est redoutable contre un roi au coin.",
    hint: "Le cavalier f6 protège h7 et contrôle g8 : la tour peut frapper.",
  },
  {
    id: 'tac-sacrifice-0007', theme: 'tactique', subtheme: 'sacrifice', difficulty: 1400,
    fen: '5rk1/5ppp/8/8/8/3B1N2/PPP5/3Q2K1 w - - 0 1',
    solution: ['Bxh7+', 'Kxh7', 'Ng5+', 'Kg8', 'Qh5'],
    explanation: "Le sacrifice grec : Fxh7+ ! Rxh7, Cg5+ Rg8, Dh5 — et la menace Dh7 mat est imparable : la tour f8 bouche la fuite du roi. Ce sacrifice fonctionne quand la dame peut rejoindre la colonne h.",
    hint: "Sacrifiez le fou sur h7, puis ramenez le cavalier et la dame vers le roi.",
  },
];

// ============================================================================
// EXERCICES SUPPLÉMENTAIRES — finales (6) et ouvertures (6)
// ============================================================================
export const EXERCISES_EXTRA = [
  // ---- Finales ----
  { id: 'fin-pions-0001', theme: 'finale', subtheme: 'pions', difficulty: 1,
    fen: '8/8/8/1k6/8/8/6P1/K7 w - - 0 1',
    solution: ['g4', 'Kc4', 'g5', 'Kd3', 'g6'],
    explanation: 'Course de pions : votre pion g file à dame pendant que le roi noir est trop loin pour l\'arrêter.',
    hint: 'Poussez votre pion sans attendre.' },
  { id: 'fin-pions-0002', theme: 'finale', subtheme: 'pions', difficulty: 2,
    fen: '4k3/8/3KP3/8/8/8/8/8 w - - 0 1',
    solution: ['e7', 'Kf7', 'Kd7'],
    explanation: 'Le pion e6 avance jusqu\'à e7, puis le roi blanc prend l\'opposition et chasse le roi noir : le pion promeut.',
    hint: 'Poussez le pion, puis placez le roi devant.' },
  { id: 'fin-tours-0001', theme: 'finale', subtheme: 'tours', difficulty: 1,
    fen: '6k1/8/6K1/8/8/8/8/R7 w - - 0 1',
    solution: ['Ra8#'],
    explanation: 'Le roi noir est cloué au coin par votre roi : Ta8 est mat.',
    hint: 'Donnez échec sur la 8e rangée.' },
  { id: 'fin-tours-0002', theme: 'finale', subtheme: 'tours', difficulty: 2,
    fen: 'k7/8/2K5/8/8/8/8/7R w - - 0 1',
    solution: ['Kb6', 'Kb8', 'Rh8#'],
    explanation: 'Approchez d\'abord le roi (Kb6) pour contrôler a7 et b7 : après Kb8, Th8 est mat.',
    hint: 'Le roi doit d\'abord contrôler les cases de fuite.' },
  { id: 'fin-tours-0003', theme: 'finale', subtheme: 'tours', difficulty: 1,
    fen: '5k2/8/5K2/8/8/8/8/1R6 w - - 0 1',
    solution: ['Rb8#'],
    explanation: 'Même technique : le roi noir est bloqué en f8 par votre roi, Tb8 est mat.',
    hint: 'Échec sur la dernière rangée.' },
  { id: 'fin-dames-0001', theme: 'finale', subtheme: 'dames', difficulty: 1,
    fen: 'k7/8/2K5/8/8/8/1Q6/8 w - - 0 1',
    solution: ['Qb7#'],
    explanation: 'Db7 mat : la dame contrôle a8, a7 et b8 pendant que le roi blanc couvre b6 et b7.',
    hint: 'Placez la dame à un pas du roi adverse, protégée par votre roi.' },
  // ---- Ouvertures ----
  { id: 'ouv-traps-0001', theme: 'ouverture', subtheme: 'pieges', difficulty: 2,
    fen: 'r1bqkbnr/pppp1ppp/8/4p3/2BnP3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: ['Nxe5'],
    explanation: 'Le cavalier d4 attaque votre pion e4 mais le pion e5 noir est en prise : Cxe5 gagne un pion (si Dxd4?? Cxf7+ fourchette).',
    hint: 'Un pion adverse est resté sans défense au centre.' },
  { id: 'ouv-traps-0002', theme: 'ouverture', subtheme: 'pieges', difficulty: 2,
    fen: 'r1bqkbnr/pppp2pp/8/4p3/4P3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 4',
    solution: ['Qh5+'],
    explanation: 'Dans la défense Damiano, les Noirs viennent de capturer le cavalier e5 — erreur fatale : Dh5+ ! et après g6, Dxe5+ attaque le roi ET la tour h8.',
    hint: 'Un échec de la dame exploite la diagonale ouverte par le pion f6.' },
  { id: 'ouv-traps-0003', theme: 'ouverture', subtheme: 'pieges', difficulty: 2,
    fen: 'r1bqkbnr/pppp1ppp/2n5/8/3NP2q/8/PPP2PPP/RNBQKB1R w KQkq - 0 1',
    solution: ['Nxc6'],
    explanation: 'La dame h4 menaçait Cxf3+, mais Cxc6 capture le cavalier en défendant tout : les Blancs gagnent une pièce.',
    hint: 'Prenez la pièce qui attaque votre cavalier f3.' },
  { id: 'ouv-principes-0001', theme: 'ouverture', subtheme: 'principes', difficulty: 1,
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    solution: ['Bc4'],
    explanation: 'Principes d\'ouverture : développer les pièces vers le centre. Fc4 vise f7 et prépare le roque.',
    hint: 'Développez une pièce maîtresse vers le centre.' },
  { id: 'ouv-principes-0002', theme: 'ouverture', subtheme: 'principes', difficulty: 1,
    fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    solution: ['O-O'],
    explanation: 'Les deux cavaliers et les deux fous sont développés : c\'est le moment de mettre le roi en sécurité par le petit roque.',
    hint: 'Mettez le roi à l\'abri.' },
  { id: 'ouv-principes-0003', theme: 'ouverture', subtheme: 'principes', difficulty: 2,
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R w KQkq - 0 4',
    solution: ['dxe5'],
    explanation: 'Le pion e5 n\'est pas défendu : dxe5 gagne un pion au centre. Les Noirs ne peuvent pas reprendre sans perdre la dame après les échanges.',
    hint: 'Un pion adverse au centre est en prise.' },
];

// ============================================================================
// LEÇONS
// ============================================================================
export const LESSONS = [
  {
    id: 'ouv-italienne-01',
    category: 'ouvertures',
    title: 'La Partie italienne (Giuoco Piano)',
    level: 'Débutant',
    intro: 'L\'une des plus anciennes ouvertures du jeu : les Blancs développent rapidement leurs pièces et visent le point faible f7.',
    sections: [
      { heading: 'L\'idée générale',
        text: 'Après 1.e4 e5 2.Cf3 Cc6 3.Fc4, les Blancs placent le fou sur la diagonale a2-g8 qui pointe vers f7, la case la plus faible du camp noir (seul le roi la défend). Le plan : développer vite, roquer, puis frapper au centre avec c3 et d4.',
        fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3' },
      { heading: 'Les premiers coups',
        text: 'Suivez la séquence : les Noirs répondent le plus souvent 3...Fc5 (le « Giuoco Piano », jeu calme). Les deux camps développent leurs cavaliers, puis les Blancs préparent la poussée d4.',
        fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
        moves: ['Bc5', 'c3', 'Nf6', 'd4', 'exd4', 'cxd4'] },
      { heading: 'Le point clé f7',
        text: 'Ce diagramme montre pourquoi f7 est fragile : le fou c4 et le cavalier g5 peuvent s\'y combiner. C\'est la base du « coup du foie » et de nombreux pièges italiens.',
        fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p1N1/2B1P3/8/PPPP1PPP/RNBQK2R b KQkq - 5 4' },
      { heading: 'À retenir',
        text: '1) Développez une pièce nouvelle à chaque coup. 2) Roquez avant le coup 10. 3) Contrôlez le centre avec vos pions. 4) Gardez un œil sur f7 (et f2 !) : c\'est là que se gagnent les parties entre débutants.' },
    ],
  },
  {
    id: 'tac-fourchette-01',
    category: 'tactiques',
    title: 'La fourchette',
    level: 'Débutant',
    intro: 'La fourchette est le motif tactique le plus fréquent : une seule pièce attaque deux cibles à la fois.',
    sections: [
      { heading: 'Qu\'est-ce qu\'une fourchette ?',
        text: 'Une pièce attaque simultanément deux pièces adverses (ou plus). L\'adversaire ne peut en sauver qu\'une : vous gagnez l\'autre. Le cavalier est le champion de la fourchette grâce à sa marche en L, imprévisible.',
        fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/4P3/3P4/PPP1NPPP/RNBQKB1R b KQkq - 0 4' },
      { heading: 'La fourchette royale',
        text: 'Le rêve de tout cavalier : sauter en c7 (ou c2) pour donner échec au roi tout en attaquant la tour du coin. Échec oblige, la tour est perdue.',
        fen: 'r1bqkbnr/pppp1ppp/2n5/8/8/2N5/PPPPPPPP/R1BQKBNR b KQkq - 2 2',
        moves: ['Nf6', 'Nd5', 'Ne4', 'Nc7+'] },
      { heading: 'Les pions aussi fourchettent',
        text: 'Ne sous-estimez pas les fourchettes de pions : un simple pion qui attaque deux pièces maîtresses gagne du matériel. Ici, le pion d4 va avancer en d5 et attaquer le cavalier ET préparer e5 contre l\'autre cavalier.',
        fen: 'r1bqkb1r/pp1ppppp/2n2n2/2p5/3PP3/5N2/PPP2PPP/RNBQKB1R w KQkq - 0 4',
        moves: ['d5'] },
      { heading: 'Comment les repérer',
        text: 'Après chaque coup adverse, demandez-vous : « Quelles cases mon cavalier (ou mon pion) pourrait-il attaquer en un coup ? » Les pièces adverses sur la même couleur de case que votre cavalier sont des cibles potentielles de fourchette.' },
    ],
  },
  {
    id: 'fin-opposition-01',
    category: 'finales',
    title: 'L\'opposition et les finales de pions',
    level: 'Intermédiaire',
    intro: 'Dans les finales roi + pion contre roi, tout se joue sur l\'opposition : l\'art de bloquer le roi adverse avec le vôtre.',
    sections: [
      { heading: 'L\'opposition directe',
        text: 'Quand les deux rois se font face avec une case d\'écart, celui qui NE doit PAS jouer « a l\'opposition » : l\'autre est obligé de céder le passage. C\'est le concept fondamental de toutes les finales de pions.',
        fen: '8/8/4k3/8/4K3/8/8/8 w - - 0 1' },
      { heading: 'Prendre l\'opposition pour avancer',
        text: 'Votre pion est en d2. Pour le faire promouvoir, votre roi doit d\'abord déborder le roi noir : prenez l\'opposition, avancez par l\'aile, chassez le roi adverse, puis poussez le pion.',
        fen: '8/8/4k3/8/4K3/8/3P4/8 w - - 0 1',
        moves: ['d4', 'Kd6', 'Kf5', 'Ke7', 'd5'] },
      { heading: 'La règle du carré',
        text: 'Un pion isolé promut si le roi adverse ne peut pas entrer dans son « carré » : tracez mentalement un carré du pion jusqu\'à la case de promotion. Si le roi adverse, au trait, ne peut pas y entrer, le pion promut sans aide.',
        fen: '8/8/8/8/1k6/8/1P6/4K3 w - - 0 1' },
      { heading: 'À retenir',
        text: '1) Roi devant le pion, pas derrière. 2) Qui n\'a pas le trait a l\'opposition. 3) Comptez le carré avant de laisser votre roi derrière. 4) En finale, chaque tempo compte : ne perdez pas un seul coup.' },
    ],
  },
];

// ============================================================================
// LEÇONS DE STRATÉGIE (ajoutées à LESSONS via LESSONS_STRATEGY)
// ============================================================================
export const LESSONS_STRATEGY = [
  {
    id: 'strat-pions-01',
    category: 'strategie',
    title: 'Structures de pions et cases faibles',
    level: 'Intermédiaire',
    intro: 'Les pions sont « l\'âme du jeu » (Philidor). Leur structure détermine les plans, les bonnes et mauvaises pièces, et les cases stratégiques.',
    sections: [
      { heading: 'Les chaînes de pions',
        text: 'Une chaîne de pions défend ses propres maillons, mais elle a deux points faibles : la BASE (le dernier pion, ici d4 pour les Blancs, f7-g6... non : e5 pour les Noirs) et les cases devant elle. Conseil de Nimzowitsch : « Attaquez la base de la chaîne ! » Les Blancs joueront c3 puis f4-f5 contre la base e5-f4 ? Non : la base noire est e5... En pratique : contre une chaîne, frappez le pion le plus reculé.',
        fen: '4k3/pp3ppp/2p1p3/3pP3/3P4/8/PPP2PPP/4K3 w - - 0 1' },
      { heading: 'Le pion isolé : force et faiblesse',
        text: 'Le pion d4 blanc est isolé : aucun pion ami ne peut le défendre. Il donne de l\'espace et des cases d\'appui (e5, c5) au milieu de jeu — jouez l\'attaque ! Mais en finale, il devient une cible. Avec le pion isolé : évitez les échanges, attaquez le roi. Contre le pion isolé : échangez les pièces, bloquez-le (cavalier en d4 !), puis gagnez la finale.',
        fen: 'r1bq1rk1/pp2bppp/2n1pn2/3p4/3P4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 1' },
      { heading: 'Les cases d\'appui (avant-postes)',
        text: 'Un avant-poste est une case avancée qu\'aucun pion adverse ne peut chasser. Le cavalier blanc en d5 est installé à demeure : il paralyse tout le camp noir. Règle d\'or : un cavalier sur un avant-poste vaut souvent une tour. Créez ces cases en chassant les pions adverses qui les défendent.',
        fen: 'r3k2r/ppp2ppp/2n5/3Nb3/8/8/PPP2PPP/R1B1K2R b KQkq - 0 1' },
      { heading: 'À retenir',
        text: '1) Identifiez la structure avant de choisir un plan. 2) Attaquez la base des chaînes. 3) Avec un pion isolé, gardez les pièces ; contre, échangez. 4) Les avant-postes de cavaliers gagnent les parties. 5) Une faiblesse de pion est éternelle — une mauvaise pièce peut bouger, un pion faible reste.' },
    ],
  },
  {
    id: 'strat-initiative-01',
    category: 'strategie',
    title: 'L\'initiative et le développement',
    level: 'Intermédiaire',
    intro: 'L\'initiative, c\'est la capacité de créer des menaces qui obligent l\'adversaire à réagir. Elle vaut souvent plus qu\'un pion.',
    sections: [
      { heading: 'Le temps est une pièce',
        text: 'À l\'ouverture, chaque coup qui ne développe pas est un cadeau à l\'adversaire. Un avantage de deux ou trois coups de développement, avec le roi adverse au centre, justifie presque toujours un sacrifice. Posez-vous la question après chaque coup adverse : « Puis-je créer une menace plutôt que de me défendre ? »',
        fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4' },
      { heading: 'Exemple de maître : Morphy écrase l\'aristocratie',
        text: 'Paul Morphy, opéra de Paris, 1858. Les Noirs viennent de jouer ...De6, menaçant apparemment de se consolider. Mais les Blancs ont TOUTES leurs pièces actives et le roi noir est au centre : Morphy conclut en cinq coups. Suivez la combinaison : élimination de la tour, puis Db8+ !! — sacrifice de dame qui dévie le cavalier — et Td8 mat. L\'un des plus beaux mats de l\'histoire.',
        fen: '1n2kb1r/p2r1ppp/4q3/1B2p1B1/4P3/1Q6/PPP2PPP/2KR4 w - - 2 15',
        moves: ['Bxd7+', 'Nxd7', 'Qb8+', 'Nxb8', 'Rd8#'] },
      { heading: 'Convertir l\'initiative',
        text: 'L\'initiative est un capital qui fond : si vous ne la convertissez pas (matériel, mat, faiblesse durable), elle s\'évapore et l\'adversaire se consolide. Quand l\'attaque n\'aboutit pas, cherchez la transformation : gagner un pion, abîmer une structure, ou échanger vers une finale favorable.',
        fen: '1n2kb1r/p2r1ppp/4q3/1B2p1B1/4P3/1Q6/PPP2PPP/2KR4 w - - 2 15' },
      { heading: 'À retenir',
        text: '1) Développement + roi adverse au centre = cherchez le sacrifice. 2) Créez des menaces à chaque coup. 3) L\'initiative non convertie disparaît. 4) La meilleure défense contre une initiative est souvent le contre-sacrifice qui rend le matériel en échange de la consolidation.' },
    ],
  },
  {
    id: 'strat-espace-01',
    category: 'strategie',
    title: 'L\'avantage d\'espace',
    level: 'Avancé',
    intro: 'Plus d\'espace signifie des pièces qui communiquent mieux. Mais l\'espace seul ne gagne pas — il faut savoir l\'utiliser sans s\'étirer.',
    sections: [
      { heading: 'Le rideau Maroczy',
        text: 'Les pions c4 et e4 (formation « Maroczy », née de la sicilienne accélérée) contrôlent d5 et b5 : les Noirs manquent cruellement de cases pour leurs pièces. Ils ne sont pas perdus — mais une seule imprécision peut suffire. Avec l\'espace : ne vous précipitez pas, étouffez d\'abord.',
        fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/2P1P3/2N2N2/PP2PPPP/R1BQ1RK1 b - - 0 1' },
      { heading: 'Le danger de la sur-extension',
        text: 'L\'espace devient une faiblesse quand les pions avancés ne peuvent plus être défendus. Ici, les pions blancs d5 et e5 sont impressionnants mais fragiles : les Noirs les attaqueront avec ...f6 et ...c6. Règle : une avancée de pions doit être soutenue par les pièces, sinon elle s\'effondre.',
        fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/2PPP3/2N5/PP3PPP/R1BQ1RK1 b - - 0 1' },
      { heading: 'Comment jouer contre l\'espace adverse',
        text: 'Trois recettes : 1) Échangez une ou deux pièces mineures — moins de pièces, moins d\'étouffement. 2) Frappez la chaîne de pions par ruptures (...b5, ...f5, ...d5) plutôt que de subir. 3) Acceptez la passivité temporaire SANS créer de faiblesse : le temps joue pour vous si la structure adverse est fragile.',
        fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/2P1P3/2N2N2/PP2PPPP/R1BQ1RK1 b - - 0 1' },
      { heading: 'À retenir',
        text: '1) L\'espace améliore la communication des pièces. 2) Avec l\'espace, empêchez d\'abord les ruptures adverses. 3) Contre l\'espace : échanges + ruptures de pions. 4) Les pions avancés non soutenus sont des cibles, pas des forces.' },
    ],
  },
  {
    id: 'strat-prophylaxie-01',
    category: 'strategie',
    title: 'Prophylaxie et jeu de restriction',
    level: 'Avancé',
    intro: 'La prophylaxie — chère à Nimzowitsch et Karpov — consiste à empêcher les plans adverses AVANT de réaliser les siens.',
    sections: [
      { heading: 'Demandez-vous : que veut mon adversaire ?',
        text: 'Avant chaque coup, la question n\'est pas « que puis-je faire ? » mais « que ferait mon adversaire si c\'était son tour ? ». Si sa réponse est dangereuse, votre priorité est de l\'en empêcher. Ici, les Noirs menacent ...Ch5 pour échanger le fou et ...f5. Le coup h3 ! des Blancs supprime les deux idées à la fois.',
        fen: 'r2q1rk1/pp1bppbp/2np1np1/8/3NP3/2N1BP2/PPPQ2PP/R3KB1R b KQ - 3 8' },
      { heading: 'La restriction avant l\'expansion',
        text: 'Karpov gagnait des parties entières sans jamais « attaquer » : il supprimait chaque contre-jeu jusqu\'à ce que l\'adversaire n\'ait plus que des coups qui se dégradent. Séquence type : 1) Identifier le seul plan actif adverse. 2) Le neutraliser. 3) ALORS avancer ses propres pions. L\'ordre compte.',
        fen: 'r2q1rk1/pp1bppbp/2np1np1/8/3NP3/2N1BP2/PPPQ2PP/R3KB1R w KQ - 4 9' },
      { heading: 'Le sur-protection',
        text: 'Concept de Nimzowitsch : surprotégez vos points stratégiques (centre, avant-postes) AVANT qu\'ils ne soient attaqués. Le pion e4, surprotégé par le cavalier c3, le fou e3, la dame d2, devient un roc qui libère les autres pièces pour l\'attaque. La sur-protection est offensive, pas défensive !',
        fen: 'r2q1rk1/pp1bppbp/2np1np1/8/3NP3/2N1BP2/PPPQ2PP/R3KB1R w KQ - 4 9' },
      { heading: 'À retenir',
        text: '1) « Que veut mon adversaire ? » avant chaque coup. 2) Empêcher un plan vaut souvent mieux qu\'en exécuter un. 3) Neutralisez d\'abord, expandez ensuite. 4) Surprotégez vos points forts. 5) La patience prophylactique use les adversaires impatients.' },
    ],
  },
];
